language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_script:
  - "pip install pytest pytest-cov python-coveralls"
install: "pip install ."
# command to run tests
script: "py.test --cov valid_model --cov-report term-missing tests.py"
after_success:
  - "coveralls"